### ISSUE TITLE
Support for UART Sensor

### ISSUE THREAD

**Issue by oskretc** [OttoWinter/esphomelib#318]
**What new integration would you wish to have?**
UART Sensor

**If possible, provide a link to an existing library for the integration:**

**Is your feature request related to a problem? Please describe.**
To address sensors that communicate via UART and perhaps other serial protocols.

**Additional context**
Many Systems use UART to output some status information. It will be great to have a generic UART sensor that can configure the UART pins, baud rate, parity, etc, retrieve the data from the uart buffer and one of the following options:
* Forward the data as is.
* Use lambdas or even Template sensors to parse the data.
* Override a parser to implement more complex functions to make sense out of the data.

I have implemented a reader for my power meter (Meter-Bus: https://en.wikipedia.org/wiki/Meter-Bus) using esphomeyaml and custom C++ sensor.

Maybe you have any ideas on how to implement such "sensor" in another way. I just couldnt find it

**Comment by OttoWinter** [comment]
Fixed by https://github.com/OttoWinter/esphomelib/pull/274

UART is an asynchronous protocol so parsing it in real time can be hard. It's impossible to develop a "UART sensor" component that would fit each use case. Solution (as in #274): make it easier to define custom UART components and custom sensors. (guides will be up for 1.10.0)
