### ISSUE TITLE
Multiple concurrent OTA

### ISSUE THREAD

**Issue by pauly7300** [OttoWinter/esphomelib#442]
**Is your feature request related to a problem/use-case? Please describe.**

I have multiple devices that are similar and have had numerous times when I would like to change one element on each device.  Currently I make a change to one device, push the change OTA.  Then repeat for each device.  

**Describe the solution you'd like**

It would be convenient if I could make all the edits and then OTA push to multiple devices (based on my selection), all at the same time.

**Additional context**

I noticed that I can do this with up to 3 devices currently if I open 3 browser windows so i'm hoping this is possible in the future.  I show this in the following video.
https://youtu.be/Dm2m2I-_vns

**Comment by OttoWinter** [comment]
No, this won't become a feature. And that mainly because the user needs to see the log output from the OTA process - if something goes wrong they must see the whole log.

If we were to display them all at once it would be a big issue to identify what line came from where. Also this solution will *always* be just as fast as you currently do it: opening multiple browser tabs.
